### ISSUE TITLE
Android: Support binary data for insert/update and query

### ISSUE THREAD

**Issue by richardliebmann** [capacitor-community/sqlite#266] opened 2022-05-06 09:55 UTC
**Is your feature request related to a problem? Please describe.**
We are trying to insert binary data into the SQLite database. It's not best practice, but we'd like to have everything together in the database. We are currently only developing a solution for Android, so it has not been tested on other platforms.

There are several issues we have identified:

- TypedArrays are not supported by Capacitor (as far as I know), so I used Number Arrays, represented as JSArray in Java
- Complex objects are not supported by sqlite in Android (only primitive types and byte[]). When we provide number[] or Uint8Array from JavaScipt I got an error (Type not supported)

**Describe the solution you'd like**
The JavaScript array type should be converted to byte[] and when we query the result it should be converted back. We have already done a test implementation https://github.com/asello/capacitor-sqlite.

**Describe alternatives you've considered**
We currently have all JSArrays parameters converted to a byte[]. Should this be configurable or is this the only use of JSArrays as parameters?

**Additional context**

**Comment by felipecarrillo100** [comment] 2022-05-06 20:03
You can use SQL syntax to upload binary data a hexadecimal string,   for this convert you binary array to a hexadecimal string and then use  X'' to indicated the string is hexadecimal data    

Here an example:
// data: ArrayBuffer;

    const sql = "INSERT OR REPLACE INTO images (id, img) VALUES( ?, X'"+ buf2hex(data) +"')" ;

Here an implementation of how to implement buf2hex

function buf2hex(buffer: ArrayBuffer) { // buffer is an ArrayBuffer
    // @ts-ignore
    return [...new Uint8Array(buffer)]
        .map(x => x.toString(16).padStart(2, '0'))
        .join('');
}

**Comment by jepiqueau** [comment] 2022-05-07 05:07
@felipecarrillo100 thanks for your smart answer. This allows to use the plugin as it is. @richardliebmann is that suggestion solve your issue.

**Comment by richardliebmann** [comment] 2022-05-07 06:15
@felipecarrillo100 thanky you, I didn't think about that. 

@jepiqueau This will solve the issue for insert/update binary data, but we won't get back the data properly. Should the query also return the data as binary hex string to be consistent?

**Comment by felipecarrillo100** [comment] 2022-05-07 07:28
To retrieve the data it is even easier because you can use the existing sql function. You will have a hex string that you can convert back to a  binary array with JavaScript.

In this example sql converts binary data to hex string, and then in JavaScript you convert the string back to a binary array. Then the binary array can be converted to a blob, or to a url to show an image like <img src=>

                const sql = "SELECT hex(img) FROM "+ tableName + " WHERE id = ?" ;
                    db.query(sql, [1]).then((result: DBSQLiteValues)=>{
                        if (result && result.values && result.values.length===1) {
                            // @ts-ignore
                            const fromHexString = (hexString:string) => new Uint8Array(hexString.match(/(..?)/g).map(byte => parseInt(byte, 16)));
                            const uint8 = fromHexString(result.values[0]["hex(img)"]);
                            const imgBlob = new Blob([uint8], {type: "octet/stream"})
                            const objectURL = URL.createObjectURL(imgBlob);
                             // do something with the data...

                        }
                    }).catch(()=>{
                    });

**Comment by richardliebmann** [comment] 2022-05-07 09:14
@felipecarrillo100 Yes, that's true, but it feels like a hack to me ;-). In my opinion, type translation should be handled in the library and decoupled from use. Especially when a orm mapper is used (e.g. type format), it is often not easy to latch into it.

**Comment by jepiqueau** [comment] 2022-05-07 16:58
@richardliebmann Seems that you have modified 2 methods `SelectSQL` in Database.java  and `objectJSArrayToArrayList` in UtilsSQLite.java. Can you confirmed. Can you share a simple example so i can look if i can make the modification in iOS, Electron and Web and test it. I do not want to have discrepancy between platforms. So i am waiting your data prior to take the decision to implement it or not

**Comment by jepiqueau** [comment] 2022-05-14 03:39
@richardliebmann if you do not reply i cannot do anything

**Comment by jepiqueau** [comment] 2022-08-07 09:48
@richardliebmann Any progress on this?

**Comment by jepiqueau** [comment] 2022-09-06 07:05
@richardliebmann As you did not provide the requested example, i consider that you are not anymore interested in. So i close the issue. Feel free to re-open it if you provide an example

**Closed by jepiqueau** 2022-09-06 07:05 UTC
