### ISSUE TITLE
Run statement changes is incorrect in browsers

### ISSUE THREAD

**Issue by mtnair** [capacitor-community/sqlite#378] opened 2023-02-17 15:49 UTC
**Describe the bug**
When running an update statement like `const res = await database.run('UPDATE table SET x = ? WHERE y = ?', [2, 1], false);`, the variable `res.changes.changes` is always `0` in the browser. When running on a device (I tested it on iOS), the variable is different from `0` and reflects the actual changed rows of the request.

**To Reproduce**
Run following code with the @capacitor-community/sqlite plugin in the browser:

```typescript
const res = await database.run('UPDATE table SET x = ? WHERE y = ?', [2, 1], false);

console.log(res.changes.changes);
```

**Expected behavior**
I expect the `res.changes.changes` to be different from `0` when there were changes made.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge (Chromium-based) / Firefox
- Version: 110.0.1587.46 / 109.0.1

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro Max
- OS: iOS 16

**Additional context**
n/a

**Comment by jepiqueau** [comment] 2023-02-18 08:08
@mtnair i will have a look thanks

**Comment by jepiqueau** [comment] 2023-02-18 17:59
@mtnair 
Well i could not reproduce. 
i have added a test in test2dbs.page of [angular-sqlite-app-starter](https://github.com/jepiqueau/angular-sqlite-app-starter/blob/master/src/app/test/test2dbs/test2dbs.page.ts) lines 108 to 113 and as you will see ```ret378.changes.changes return 1``` which is correct.
Can you share a replicate of your app just demonstrating the problem on github , check also your code

**Comment by jepiqueau** [comment] 2023-02-24 13:38
@mtnair Any progress on your side ?

**Comment by jepiqueau** [comment] 2023-02-26 07:52
@mtnair No feedback so i close the issue. feel free to reopen it if required

**Closed by jepiqueau** 2023-02-26 07:52 UTC
