### ISSUE TITLE
DELETE FROM does not work

### ISSUE THREAD

**Issue by muuvmuuv** [capacitor-community/sqlite#271] opened 2022-05-11 11:57 UTC
**Describe the bug**

I cannot longer `DELETE FROM`. Am I required to add a `sql_deleted` now? This does not match our design/model and we have no upstream database to sync with. Can we have the old behaviour back or at least add an option like "strict" mode or something like that. We really need to *remove* everything not update a table col.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] iPhone 13 Pro
- OS: [e.g. iOS8.1] latest
- Version [e.g. 22] latest

**Additional context**

**Comment by jepiqueau** [comment] 2022-05-11 16:20
@muuvmuuv do you have a last_modified column and/or a synchronisation table?

**Comment by muuvmuuv** [comment] 2022-05-11 21:12
Nope, :/ just five tables with some foreign keys. Really nothing special. I was able to get it to work with 3.4.2. Evey release after that just fails, I mean it does not delete nor prints an error. I havent checked if its add these columns.

**Comment by jepiqueau** [comment] 2022-05-12 05:03
@muuvmuuv  Which platform?

**Comment by jepiqueau** [comment] 2022-05-12 05:29
@muuvmuuv i could not reproduce the error see implementation of `issue271` in [capacitor-solid-sqlite](https://github.com/jepiqueau/capacitor-solid-sqlite). You MUST not have a column `last_modified` in your tables

**Comment by muuvmuuv** [comment] 2022-05-12 08:07
I tested on iOS. We have no last_modified table or anything special.

**Comment by muuvmuuv** [comment] 2022-05-12 08:35
@jepiqueau just found it. Don't ask me how and why, but when you forget the leading `;` it does not delete anything nor errors. Just tested with your shared repo. Just replace the the sql stmts in your try/catch with this:


```ts
            await db.executeSet(fiveContacts);

            res = await db.query("SELECT * FROM contacts");
            console.log("BEFORE:",res);

            res = await db.execute("DELETE FROM contacts");

            res = await db.query("SELECT * FROM contacts");
            console.log("AFTER:",res);

            await db.executeSet(fiveContacts);
```

**Comment by jepiqueau** [comment] 2022-05-12 13:23
@muuvmuuv what do you mean by 'when you forget the leading'

**Comment by jepiqueau** [comment] 2022-05-12 16:11
@muuvmuuv 

if you do this 
```
           await db.executeSet(fiveContacts);

            res = await db.query("SELECT * FROM contacts");
            console.log("BEFORE:",res);

            res = await db.execute("DELETE FROM contacts");

            res = await db.query("SELECT * FROM contacts");
            console.log("AFTER:",res);

```
you get this
```
⚡️  [log] - **** Show Contacts before DELETE ****
⚡️  [log] - >>> id: 1 name: Jackson email: Jackson@example.com
⚡️  [log] - >>> id: 2 name: Bush email: Bush@example.com
⚡️  [log] - >>> id: 3 name: Jones email: Jones@example.com
⚡️  To Native ->  CapacitorSQLite execute 42866326
⚡️  [log] - >>> id: 4 name: Kennedy email: Kennedy@example.com
⚡️  [log] - >>> id: 5 name: Jeep email: Jeep@example.com
⚡️  TO JS {"changes":{"changes":5}}
⚡️  To Native ->  CapacitorSQLite query 42866327
⚡️  [log] - delete execute res: {"changes":{"changes":5}}
⚡️  TO JS {"values":[]}
⚡️  [log] - **** Show Contacts final ****

```
When you executeSet you get five changes and when you do the delete you get also  five changes and no contacts are returned from the select. This is correct
So i do not understand your case.

**Comment by jepiqueau** [comment] 2022-05-12 16:12
@muuvmuuv Can you give your package.json file

**Comment by muuvmuuv** [comment] 2022-05-12 19:02
I used the repo you shared and just installed missing deps like your stencil sqlite and sql.js. 

This is strange. I have tested it ten times. Adding a semicolon at the end of "DELETE FROM xxx" and removing it have two different behaviours.

**Comment by jepiqueau** [comment] 2022-05-13 04:24
@muuvmuuv you must not install Stencil jeep-sqlite and sql.js. there are installed when you install @capacitor-community/sqlite. It works as it is

**Comment by jepiqueau** [comment] 2022-05-13 04:26
@muuvmuuv i notice that in the code you give above you call two times `await db.executeSet(fiveContacts)`

**Comment by muuvmuuv** [comment] 2022-05-13 06:03
I had to. I use pnpm and it was required. Anyway that aint the problem. 

Yeah just to trst but the query to get is right before and after the delete so it doesnt matter. 

Let me test it again and create a PR

**Comment by victorybiz** [comment] 2022-05-15 00:50
The recent release is causing errors in our delete functions, as we have a last_modified column in most of our tables but we use our `custom database synchronization` strategy, we are not using `importFromJson` and `exportToJson`.

Is there an option to turn off this new default behaviour?

**Comment by jepiqueau** [comment] 2022-05-15 09:48
@victorybiz the last_modified is a reserved column name for capacitor-community/sqlite. You must rename yours in each of your tables and it will work fine.

**Comment by victorybiz** [comment] 2022-05-15 10:55
@jepiqueau Thanks for the response, this will be tough though because we have 100+ tables, we have to do these updates on the production serverless DB as well to maintain the same structure including the recreation of all indexes.

**Comment by jepiqueau** [comment] 2022-05-15 11:03
@victorybiz OK i understand i will add to the test the existence of the sql_deleted column that hopefully you do not use in your tables. It will be part of the next release. I amquite busy on private things right now meaning that you will have to wait till i get some free time.

**Comment by jepiqueau** [comment] 2022-05-15 11:18
@victorybiz which platform are you using ?

**Comment by victorybiz** [comment] 2022-05-15 11:44
@jepiqueau Thank you so much, I will really appreciate this. We currently use it on all platforms; Android, iOS, Electron and Web, it's a cross-platform app.

**Closed** 2022-05-16 04:28 UTC

**Comment by jepiqueau** [comment] 2022-05-16 04:50
@victorybiz this has been fixed in 3.5.1-1

**Comment by victorybiz** [comment] 2022-05-16 19:34
@jepiqueau Thank you so much for this update.

**Comment by muuvmuuv** [comment] 2022-05-17 09:12
My issue continues to occur. You can reproduce it here: https://github.com/muuvmuuv/issue-capacitor-sqlite/commit/9d0e472c148c300b394435de06ff348907c0a0bc

It did fix it though by adding the semicolon at the end of the delete statement. I guess the newer version is somehow "stricter" in syntax.

**Comment by jepiqueau** [comment] 2022-05-17 09:26
@muuvmuuv if you do a db.execute you must have a semi column as a db.execute could have several statement which is not the case of a db.run

**Comment by muuvmuuv** [comment] 2022-05-17 10:28
Did not know that. Nice to know, I need to update some statements now

**Comment by victorybiz** [comment] 2022-05-31 00:32
Greetings @jepiqueau , I just discovered this issue still exist in `iOS` platform. Delete not working on iOS with `ERROR MESSAGE:  {"errorMessage":"Run: Failed in runSQL :  Error: prepareSQL prepare failed rc: 1 message: no such column: sql_deleted"`.

**Comment by jepiqueau** [comment] 2022-05-31 07:30
@victorybiz read the doc you need now to adda column sql_deleted on each of your tables to be able to synchronize the deleted éléments between to exportToJson

**Comment by victorybiz** [comment] 2022-05-31 08:35
@jepiqueau You did fix this in the last release for users who are NOT using the package's provided `synchronization` (`importFromJson` and `exportToJson`) feature nor have `sql_deleted` column BUT have the `last_modified` column in all their tables for their custom database synchronization. The fix in the last release works on Web, Android and Electron platforms but does not work on `the iOS` platform, still shows the `sql_deleted` column not found error when running a DELETE statement.

**Comment by rengadevigg** [comment] 2023-11-17 18:07
> I used the repo you shared and just installed missing deps like your stencil sqlite and sql.js.
> 
> This is strange. I have tested it ten times. Adding a semicolon at the end of "DELETE FROM xxx" and removing it have two different behaviours.

yes. 'DELETE FROM XXX;` IT WORKS BUT 'DELETE FROM XXX` DIDNT DELETE

**Comment by jepiqueau** [comment] 2023-11-19 07:44
@rengadevigg are you using db.execute, db.run or db.executeSet? If you are using db.execute the ; is mandatory at the end as the db.execute takes à list of statements

**Comment by rengadevigg** [comment] 2023-11-19 07:49
> @rengadevigg are you using db.execute, db.run or db.executeSet? If you are using db.execute the ; is mandatory at the end as the db.execute takes à list of statements

I mean i put semicolon at the end of the statement.that does not work but if i send ; with query it works. do i make sense?

**Comment by jepiqueau** [comment] 2023-11-19 09:18
@rengadevigg query is made for SELECT statement and not for DELETE statement for this you must use RUN or EXECUTE with à semi column at the end

**Comment by rengadevigg** [comment] 2023-11-19 12:35
> @rengadevigg query is made for SELECT statement and not for DELETE statement for this you must use RUN or EXECUTE with à semi column at the end
<img width="1156" alt="Screenshot 2023-11-19 at 6 04 08 PM" src="https://github.com/capacitor-community/sqlite/assets/96510881/a82f033a-6598-4bc4-92af-50e6dee1c765">
For the confirmation. u mentioned semicolon is this wat it should be?

**Comment by jepiqueau** [comment] 2023-11-20 07:03
@rengadevigg yes like every SQLite statement

**Comment by jigeshraval** [comment] 2024-02-27 07:48
Yes, i was facing the same issue, adding ";" at the end of the query statement worked in iOS, though it is to be noted that this was only happening in iOS, in android devices, this was working as expected even without ";"
