### ISSUE TITLE
Batch insert is slow either using query or execute

### ISSUE THREAD

**Issue by fbalbinoribeiro** [capacitor-community/sqlite#464] opened 2023-08-30 16:38 UTC
**Is your feature request related to a problem? Please describe.**
We are trying to use either query or execute methods to do a batch insert and it's working. However, the insert is very slow, and we tried several ways to speed up it a little, like:
- Creating the indexes just after the insert
- Changing the Pragma Mode to MEMORY and turning off the synchronization
- Create a batch insert instead of individual inserts
- Have focused ways per OS. It seems that Query works better for iOS and Execute works better for Android.

None of them solved the problem, but they made the app slightly faster. It's not sufficient to solve our problems, tough.

**Describe the solution you'd like**
Do you have any suggestions on how to handle it?
Is there a specific method for batch inserts?

**Describe alternatives you've considered**

**Additional context**
<img width="656" alt="image" src="https://github.com/capacitor-community/sqlite/assets/24640288/f6898f93-9c3d-447a-9afa-bdf28fbb0d9f">

**Comment by jepiqueau** [comment] 2023-09-01 08:29
@fbalbinoribeiro Well query method is not made to make insert but only select. Can you give more info on your batch and how large is it. looking at your execute method i do not thing it is a good idea to saveToStore after each execute command as this is time consuming but this apply only for Web. The best is to share a small repro of your app so i can look at it with more detail.

**Comment by jepiqueau** [comment] 2023-09-07 05:47
@fbalbinoribeiro Any news can you share your code and your batch insert commands so i can have a look

**Comment by fbalbinoribeiro** [comment] 2023-09-07 16:12
@jepiqueau sorry for the delay. I'll send some piece of codes for you.

A little more context:
- We tried to use just `execute` method for everything, but the iOS froze when doing massive sequential insert operations.
- Before we were wrongly using the `query` method for everything, and it made memory leaks on Android. Then, when we changed to always use the `execute` method, we started seeing iOS frozen. That's why we are splitting it up.
- Our code is a little tricky because we use NgRX and the logic is within it. I will try to show some piece of code that does the calls.

1 - This is called sequentially and a huge amount of times on the loading functionality:
```javascript
  saveTheDownloaded$ = createEffect(() =>
    this.actions$.pipe(
      ofType(Actions.newDownloaded),
      concatMap(({ info }) => from(this.databaseService.upsertByQuery(info))),
      map(() => Actions.saved()),
    )
  );
```
It has a big size of information (like some MB's).

2 - Then, we are using that wrapper that I've created:
```javascript
 async upsertByQuery(query: string): Promise<boolean> {
      if (this.infoService.isIos()) {
        await this.query(query);
      } else {
        await this.execute(query);
      }

      return true;
  }
```
All these codes that I show you run several times. In the end, about 1GB of information could be inserted.
That combination was the best insert result that we had found specifically.

3 - These are the pragma journal codes:
```javascript
  async setPragmaJournalModeToWal() {
    await this.query('PRAGMA journal_mode = MEMORY; PRAGMA synchronous = OFF');
  }

  async setPragmaJournalModeToDelete() {
    await this.query('PRAGMA journal_mode = DELETE; PRAGMA synchronous = ON');
  }
```
We set the pragma to `memory` at the very beginning of the loading operation and set it back only when everything is inserted.

4 - To try to speed up a little more, I'm only creating the indexes after all the inserts have been made.

Thanks a lot for your help.
Any further questions that you want for me, feel free to ask me.

**Comment by jepiqueau** [comment] 2023-09-08 12:14
@fbalbinoribeiro Can you give the database schema and some  insert command that you do with some data  example so i can trye recreating the issue. I never used NgRx and neither modifies the pragma journal_mode and synchronous like you did. May be the issue is due to the cache_size so you may play with this

**Comment by jepiqueau** [comment] 2023-09-26 07:14
@fbalbinoribeiro as i do not get feedback i close the issue

**Closed** 2023-10-01 05:21 UTC
