### ISSUE TITLE
in iOS - executeSet: transaction not committed when there are no changes

### ISSUE THREAD

**Issue by bkostjens** [capacitor-community/sqlite#220] opened 2022-02-07 14:48 UTC
**Describe the bug**
When you run executeSet on iOS and the set does not make any changes a second call to executeSet will result in an error that you cannot run a transaction in a transaction.

**To Reproduce**
run executeSet (with transaction to true) twice for the same set (or any set that does not result in any db changes). This works fine on android, however it results in an error on iOS.

On code inspection I found that in Database.swift (on line 313) there is a check:

` if changes > 0 && transaction {`

When you remove the ` changes > 0 ` check all works fine. This check is not found in the android source (Database.java)

**Expected behavior**
When running executeSet multiple times (with transaction = true) I expect not to get errors that a transaction in a transaction is not supported.

**Desktop (please complete the following information):**

- OS: macOS 12.1
- n/a

**Smartphone (please complete the following information):**

- Device: iPhone XR
- OS: iOS 15.3

**Comment by jepiqueau** [comment] 2022-02-08 07:50
@bkostjens Can you share your ExecuteSet statements? Any insert or update will create a change so i cannot reproduce

**Comment by bkostjens** [comment] 2022-02-08 07:53
Im using a WHERE clause which can cause that there will be no update happening:

`INSERT INTO projectobjects (localid, serverid, name, objecttype, parent, created, lastupdate, permission)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                ON CONFLICT(localid) DO UPDATE SET
                  name = excluded.name,
                  parent = excluded.parent,
                  lastupdate = excluded.lastupdate,
                  permission = excluded.permission
                WHERE excluded.lastupdate > projectobjects.lastupdate;`

**Comment by jepiqueau** [comment] 2022-02-08 13:31
@bkostjens This should have been fixed in 3.4.0-1 Can you test and revert to me

**Comment by bkostjens** [comment] 2022-02-08 13:52
Just tested and it works fine now. Thanks again!

**Closed** 2022-02-08 14:19 UTC
