### ISSUE TITLE
Changing encryption Key after build

### ISSUE THREAD

**Issue by Youssefraqui** [capacitor-community/sqlite#90] opened 2021-03-06 11:01 UTC
First of all, a big thanks for the effort to come up with this great capacitor library which will help a lot in interacting with SQLite databases.
I read your docs and i seems that we need to set yp the encryption key befor building the application, but what if i need to define a custom key per each application user. Therefore, i need to define the encryption key at the application install in each user device, is thete a way to do so? 
Also is SQLcipher dependency free to use or we need a licence for commercial use?
Thanks a lot in advance

**Comment by jepiqueau** [comment] 2021-03-06 18:42
@Youssefraqui First thanks for looking at the plugin. I understand the question which in fact is the same than issue#88. The only way i saw is to let the user giving the secret after the first installation and store it in a storage which is may be not really safe. For SQLCipher i use only the SQLCipher Community Edition which is  open source see `https://www.zetetic.net/sqlcipher/open-source/`

**Comment by noerw** [comment] 2021-03-10 12:47
duplicate of #88, where I continued the discussion :)

**Closed** 2021-05-02 06:07 UTC
