### ISSUE TITLE
Backup/restore solution

### ISSUE THREAD

**Issue by imike57** [capacitor-community/sqlite#485] opened 2023-11-05 14:39 UTC
Hello,
First of all, thank you for this plugin!

I'm trying to create a backup/restore solution for a database. I want to import a database to replace another one currently in use.

I've tried using the `addSQLiteSuffix` and `moveDatabasesAndAddSuffix` methods. These methods work well when the database is not already present in my "databases" folder. However, for an existing database, it doesn't work, and it doesn't produce any specific errors.

I've tried the following:

```ts
await this.db.close();
await this.sqlService.sqlite.moveDatabasesAndAddSuffix("cache");
```

or

```ts
await this.db.delete();
await this.sqlService.sqlite.moveDatabasesAndAddSuffix("cache");
```

The database is successfully removed from the folder, but the database present in the "cache" folder is not copied.

Maybe there is a better approach?

I'm using Ionic with Angular.
    "@capacitor-community/sqlite": "^5.4.2-1",

**Comment by jepiqueau** [comment] 2023-11-05 17:08
@imike57 is that happen for Web platform or iOS or Android platforms or Electron platform?

**Comment by imike57** [comment] 2023-11-05 17:16
@jepiqueau 
For Android plaform.

**Comment by jepiqueau** [comment] 2023-11-07 07:47
@imike57 I cannot reproduce the issue. i did this and it works

```
    this.log += "* Starting testissue485 *\n";
    // Fetch the database
    let response = await fetch("https://raw.githack.com/jepiqueau/angular-sqlite-app-starter/26ca67486713fc9b6ea4a37a889f0fd189c18926/src/assets/databases/dbForCopy.db");
    this.log += "  > fetched 'dbForCopy' from github\n";
    let dbBlob = await response.blob();
    let base64Db = await this.getBlobAsBase64(dbBlob);
    this.log += "  > converted 'dbForCopy' to base64\n";
    // Save to cache
    await Filesystem.writeFile({ data: base64Db, path: "dbForCopyCache.db", directory: Directory.Cache });
    this.log += "  > saved 'dbForCopyCache.db' in cache folder\n";
    // Move database from cache to the device database folder
    await this._sqlite.moveDatabasesAndAddSuffix("cache");
    this.log += "  > moved 'dbForCopyCache' to databases folder\n";
    // Open the database
    let db = await this._sqlite.createConnection("dbForCopyCache", false, "no-encryption", 1);
    if (db == null) throw new Error("createConnection dbForCopyCache failed");
    await db.open();
    this.log += "  > open 'dbForCopyCache' successful\n";
    // Read from database
    let res = await db.query("SELECT * FROM areas");
    console.log(`Query 3 res.values.length: ${res.values.length}`)
    if (res.values.length !== 3 ||
      res.values[0].name !== "Access road" ||
      res.values[1].name !== "Accessway" ||
      res.values[2].name !== "Air handling system") {
      throw new Error("Query 3 areas failed");
    }
    this.log += "  > Query 3 areas 'dbForCopyCache' successful\n";
    // Insert some new areas
    let sqlcmd: string =
    "INSERT INTO areas (name, favourite) VALUES ('Gas Detector System', 1),('Gas Fire Extinguisher', 0)";
    let ret = await db.run(sqlcmd,[]);
    // Read from database
    res = await db.query("SELECT * FROM areas");
    console.log(`Query 5 res.values.length: ${res.values.length}`)
    if (res.values.length !== 5 ||
      res.values[0].name !== "Access road" ||
      res.values[1].name !== "Accessway" ||
      res.values[2].name !== "Air handling system" ||
      res.values[3].name !== "Gas Detector System" ||
      res.values[4].name !== "Gas Fire Extinguisher"
      ) {
      throw new Error("Query 5 areas failed");
    }
    this.log += "  > Query 5 areas 'dbForCopyCache' successful\n";
    await this._sqlite.closeConnection("dbForCopyCache");
    this.log += "  > closeConnection 'dbForCopyCache' successful\n";
  }

  private getBlobAsBase64(blob: Blob): Promise<string> {
    return new Promise((resolve, _) => {
      let reader = new FileReader();
      reader.onload = (event: any) => {
        resolve(event.target.result);
      };
      reader.readAsDataURL(blob);
    });
  }

```
i run it several time and it works for any run meaning that the database is well copied from cache to the database folder even if it  already exists in the database folder.
You will need to share a repro code of your issue

**Comment by jepiqueau** [comment] 2023-12-11 06:29
@imike57 Did you try to implement my suggested code?, is this fix your issue? if not can you detail more what you want to achieve otherwise can you please close the issue.

**Comment by jepiqueau** [comment] 2023-12-21 07:33
@imike57 As i did not get any feedback from you, i close the issue. Feel free to re-open it if required and share a repository of your app.

**Closed by jepiqueau** 2023-12-21 07:33 UTC
