### ISSUE TITLE
Getting sporadic "Database someDatabase.db not opened" and "No available connection for database" errors in Vue app

### ISSUE THREAD

**Issue by mpwoodward** [capacitor-community/sqlite#338] opened 2022-10-21 19:08 UTC
# Overview

This might be semi-related to #293 but in a nutshell this is my first Ionic/Vue/SQLite app and I'm wondering about the best way to manage connections, specifically:
 1. How best to use an existing connection or create a new one as needed; and
 2. Best practices around opening and closing connections across multiple components

The specific errors I'm sporadically seeing in the console (and note that thus far this is in a web browser, not on device emulators or hardware):
 1. Database [database filename] not opened
 2. No available connection for [database name]

I can't share the code for the entire app but if the chunks I share here aren't enough I'll create a sample app to illustrate what I'm doing.

This is an "offline first" app, and as a high-level overview, when a component needs data I'll do this:
 1. Check if the device has a network connection
 3. If it has a network connection, get data from the API and insert/update the SQLite database
 4. In all cases, do a SELECT from SQLite to return the relevant data to the component

(Yes, the caching process could use some refinement for efficiency, but that's where it stands now and performance is good.)

**REGARDING THE CODE BELOW, MY MAJOR QUESTION IS THIS:** Is the approach I'm taking more or less an OK way to do things, or is there some fundamental flaw in this approach that may be causing the issues I'm seeing?

# The Code

In order to not have redundant code related to SQLite connections everywhere, I put the following in a `DatabaseService.ts` file:
```typescript
const getDatabaseConnection = async (dbName: string, readonly = false) => {
  const sqlite: SQLiteConnection = new SQLiteConnection(CapacitorSQLite)
  const ret = await sqlite.checkConnectionsConsistency()
  const isConn = (await sqlite.isConnection(dbName, readonly)).result

  let db: SQLiteDBConnection

  if (ret.result && isConn) {
    db = await sqlite.retrieveConnection(dbName, readonly)
  } else {
    db = await sqlite.createConnection(dbName, false, 'no-encryption', 1, readonly)
  }

  return db
}
```

Then I have several "data service" TypeScript files that do this sort of thing:
```typescript
const getSomeData = async () => {
  if (navigator.onLine) {
    // WE HAVE A CONNECTION SO GET DATA FROM API AND UPDATE THE SQLITE DATABASE
    try {
      const apiRes = await axios.get(THE_URL)

      if (apiRes?.data.length !== 0) {
        const dataToInsert = [] as any[]
        apiRes.data.forEach((el: any) => {
          dataToInsert.push([el.foo, el.bar, el.baz])
        })

        const dataPlaceholders = dataToInsert.map(() => '(?, ?, ?)'.join(',')

        const dbRW = await getDatabaseConnection('mydb')
        await dbRW.open()

        const theQuery = `SQL INSERT/ON CONFLICT DO UPDATE HERE WITH PLACEHOLDERS;`

        await dbRW.run(theQuery, dataToInsert.flatMap((el) => el))

        await dbRW.close()
      }
    } catch (err) {
      console.log(err)
    }
  }

  // WHETHER OR NOT WE HAVE A CONNECTION GET THE DATA FROM THE DATABASE
  const dbRO = await getDatabaseConnection('mydb', true)
  await dbRO.open()

  const sqliteRes = await dbRO.query(`SOME SELECT STATEMENT HERE;`)
  
  await dbRO.close()

  const dataToReturn = [] as SomeType[]
  sqliteRes?.values?.forEach((el: any) => {
    const record: SomeType = {
      id: el.id,
      name: el.name,
    }
    dataToReturn.push(record)
  }

  return dataToReturn
}
```

And then in a Vue component I'll do something like this which interacts with a Pinia store:
```typescript
import { onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useSomeStore } from './SomeStore'

const someStore = useSomeStore()
const { someData } = storeToRefs(someData)

onMounted(async () => {
  await someStore.setSomeData()
}
```

And lastly, in the Pinia store I'll import the relevant data functions and call those there:
```typescript
import { defineStore } from 'pinia'
import { getSomeData } from '@/services/data/SomeDataService'

export const useSomeStore = defineStore('SomeStore', {
  state: () => {
    return {
      someData: [] as SomeType[],
    }
  },

  actions: {
    async setSomeData() {
      this.someData = await getSomeData()
    }
  },

  getters: {
    getTheData: state => state.someData
  }
})
```

As I click around in the app it'll work fine for a stretch, but (and this is a bit anecdotal) particularly if I'm making two data-related calls in `onMounted` in a Vue component, that seems to be where the db not open/no connection for db errors start to appear.

Thanks for any thoughts and suggestions anyone might have!

**Comment by jepiqueau** [comment] 2022-10-22 06:43
@mpwoodward looking at the code quickly i do e not find an obvious reason . The best would be that you share a demo app reproducing the issue so i could understand where the error occurs and the reason for it.

**Comment by jepiqueau** [comment] 2022-10-23 15:19
@mpwoodward  I create an application [vue-sqlite-issue336](https://github.com/jepiqueau/vue-sqlite-issue336) to try reproducing the issue and using the code you sent above with some modifications.
I suspect that the error could come from the fact that you redefine
`const sqlite: SQLiteConnection = new SQLiteConnection(CapacitorSQLite)` each time you are using `getDatabaseConnection` especially that you never close any connection, you close only the db
so i define a singleton in main.ts containing the SQLiteConnection and the platform  and use the composition API to provide this singleton and inject it in each different component that you may use. In my example,  i have only the HomePage component but i could have severals. 
Having done this, i modify the different services and the pinia store till i made it working in the onMounted method. it was not done in the first go as i got some strange behaviors .
the singleton can be injected in component but not in services so i add to pass it in argument of each method of the services.
Voilà, may be, one more familiar than me in Vue3 can do better but as it is it seems to work as i could not reproduce the issue.
Hope this can help you for your app.

**Comment by mpwoodward** [comment] 2022-10-23 17:07
@jepiqueau THANK YOU SO MUCH! That definitely clears up the confusion on my part about the connection as compared to simply opening and closing the database. This is tremendously helpful. Originally in my app I was passing the connection in which seemed weird hence why I moved to the getDatabaseConnection() function, but it totally makes sense how this would cause the issues I'm seeing. I'll rework things based on this info.

Thanks so much again, and thanks for all your hard work on this project! Very much appreciated.

**Comment by mpwoodward** [comment] 2022-10-23 18:10
@jepiqueau I'm looking through your sample code (thanks again for putting that together!) and had unless I'm missing it, I notice that `closeConnection()` is never explicitly called on the `SQLiteConnection`. Does that simply not need to be called explicitly because there's some connection management functionality that will handle that?

As you can probably gather I'm new to using SQLite with Ionic and Vue so I really appreciate your patience with my rudimentary question.

Thanks!

**Comment by jepiqueau** [comment] 2022-10-23 19:00
@mpwoodward basically if you create a connection you must close at some point when not needed anymore. It could be when you unMount the component. If you  want to use a connection in several components   you can open it in the app or in one component whic is called first and just retrieve the connection when opening the next component. In my example i did not close it as i did know what you want to do after and i was trying to reproduce the error in waiting your demo app but you can add it in the unMount method.

**Comment by mpwoodward** [comment] 2022-10-23 19:46
@jepiqueau Makes sense! Thanks for the additional explanation. I really appreciate your help!

**Comment by jepiqueau** [comment] 2022-10-24 11:54
@mpwoodward i did upgrade [vue-sqlite-issue336](https://github.com/jepiqueau/vue-sqlite-issue336) by adding a PopulationPage called from the HomePage to demonstrate the closeConnection in the onBeforeUnmount method.
Hope with this you can start modifying your app Have a good development. I will close the issue feel free to re-open it if needed

**Closed** 2022-10-24 12:10 UTC

**Comment by mpwoodward** [comment] 2022-10-24 19:33
@jepiqueau Fantastic, thanks! I'm rolling along pretty well and can't thank you enough for the help. I did discover when I'm first creating and populating the database I have to explicitly call saveToStore() on the connection, otherwise the schema and data don't seem to get committed, but between that and managing the connections as you do in your sample app things are working quite well. Thanks so much! If you have a virtual tip jar somewhere please point me in that direction. :-)
