### ISSUE TITLE
SqliteText  always  getting  null  even  i  have  value in  Database

### ISSUE THREAD

**Issue by vikashsingh009** [capacitor-community/sqlite#50] opened 2020-10-29 09:47 UTC
**Describe the bug**
i  am  doing  select  query  on  Sqlite database and  usign  SqliteUtill  getColumnValue  but  when  i am  debugging i  am  always  getting column  value  null
**To Reproduce**

1. prepare  select  query  like  select *  from  user 
2.   create  conection
3. Query SqliteUtll getColumn  type  and  which will  return  Varchar  and  then  response as always  null  even  if  my  db  have  data 
https://github.com/capacitor-community/sqlite/blob/master/ios/Plugin/Utils/UtilsSQLite.swift#L104
**Expected behavior**

**Screenshots**
https://github.com/capacitor-community/sqlite/blob/master/ios/Plugin/Utils/UtilsSQLite.swift#L104

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jepiqueau** [comment] 2020-10-29 12:22
@vikashsingh009  Can you share your database table schema for user. Can you also share the code so i can reproduce the error

**Comment by vikashsingh009** [comment] 2020-10-29 12:34
Hello @jepiqueau ,here  is  the  schema for  the  DB

![image](https://user-images.githubusercontent.com/7962189/97573527-eb554e00-1a0f-11eb-8563-a643a15ede5f.png)

```
func getUserData(_ call: CAPPluginCall) -> Observable<[[String: Any]]? > {
        var query : String = QueryService.isTableExistInSQLite(db: "sqlite_master", type: "table", tableName: "User")
        var query1: String =  "select latitude from images"
         var sqlitedbinst = SqliteDbInstance()
              let sqlite = sqlitedbinst.getSQLiteDBInstance(call)
     

        let jsArray = [String]()
        let obj  =  sqlite.customquery(statement: query, values: jsArray, call)
  

       return   Observable.just(obj)
       

    }
	func customquery(statement : String ,values : [String], _ call: CAPPluginCall) -> [[String: Any]]?  {
      

        var ret : [String] = ["null"]

        var res: [[String: Any]]?
       

        var vals = [String]()
       

        if (values.count > 0){
                     

           for i in 0..<values.count {

            let data      = values[i]

            vals.append(data)

            }

            var pluginOptions : [String: Any]? = call.getObject("pluginOptions")

            let  json =  JSON(pluginOptions)

            var encrypted =  json["encrypted"].boolValue

            var dbName =  json["database"].string!
                             var inMode  = json["mode"].string
     

            do{

               // var dbhelper = try DatabaseSQLiteHelper(databaseName: dbName, encrypted: encrypted, newsecret: inMode!, databaseVersion: 1)
              
                   mDb = try DatabaseSQLiteHelper(databaseName: "VisurConstructionDBSQLite.db")

                res =   try mDb?.selectSQL1(sql: statement, values: values)
              

            }catch{

                print("Error in Custom Select Sql ")

            }

        }else{

            do{

                mDb = try DatabaseSQLiteHelper(databaseName: "VisurConstructionDBSQLite.db")

                var pluginOptions : [String: Any]? = call.getObject("pluginOptions")
                           
                                    let  json =  JSON(pluginOptions)
                               

                                  var encrypted =  json["encrypted"].boolValue

                           var dbName =  json["database"].string!

                                  



                                  var inMode  = json["mode"].string

                           

                           

                               var dbhelper = try DatabaseSQLiteHelper(databaseName: dbName, encrypted: encrypted, newsecret: inMode!, databaseVersion: 1)

                res =   try mDb?.selectSQL1(sql: statement, values: [String]())



            }catch{}

            

        }

        return res

        
          }

  func selectSQL1(sql: String, values: [String]) throws -> [[String: Any]] {
               guard let mDB: OpaquePointer = try
                        UtilsConnection.getReadableDatabase(filename: self.path,
                       secret: secret) else {

               throw DatabaseHelperError.dbConnection(message: "Error: DB connection")

           }

           var result: [[String: Any]] = []

           var message: String = ""
    

           do {
              result = try querySQL1(mDB: mDB, sql: sql, values: values)

           } catch DatabaseHelperError.querySql(let msg) {

               message = msg

           }

           closeDB(mDB: mDB, method: "selectSQL")

           if message.count > 0 {

               throw DatabaseHelperError.selectSql(message: message)

           } else {

               return result

           }

       }
     func querySQL1(mDB: OpaquePointer, sql: String, values: [String]) throws -> [[String: Any]] {

           var selectSQLStatement: OpaquePointer?

           var result: [[String: Any]] = []

           var message: String = ""

           var returnCode: Int32 = sqlite3_prepare_v2(mDB, sql, -1, &selectSQLStatement, nil)

           if returnCode == SQLITE_OK {

               if !values.isEmpty {

               // do the binding of values

                   message = UtilsBinding.bindValues(handle: selectSQLStatement, values: values)

               }

               if message.count == 0 {

                   do {

                       result = try UtilsSQLite.fetchColumnInfo1(handle: selectSQLStatement)

                  

                   } catch DatabaseHelperError.fetchColumnInfo(let message) {

                       throw DatabaseHelperError.querySql(message: message)

                   }

               }

           } else {

               let errmsg: String = String(cString: sqlite3_errmsg(mDB))

               message = "Error: querySQL prepare failed rc: \(returnCode) message: \(errmsg)"

           }

           returnCode = sqlite3_finalize(selectSQLStatement)

           if returnCode != SQLITE_OK {

               let errmsg: String = String(cString: sqlite3_errmsg(mDB))

               message = "Error: querySQL finalize failed rc: \(returnCode) message: \(errmsg)"

           }

           if message.count > 0 {

               throw DatabaseHelperError.querySql(message: message)

           } else {

               return result

           }

       }



func querySQL1(mDB: OpaquePointer, sql: String, values: [String]) throws -> [[String: Any]] {

           var selectSQLStatement: OpaquePointer?

           var result: [[String: Any]] = []

           var message: String = ""

           var returnCode: Int32 = sqlite3_prepare_v2(mDB, sql, -1, &selectSQLStatement, nil)

           if returnCode == SQLITE_OK {

               if !values.isEmpty {

               // do the binding of values

                   message = UtilsBinding.bindValues(handle: selectSQLStatement, values: values)

               }

               if message.count == 0 {

                   do {

                       result = try UtilsSQLite.fetchColumnInfo1(handle: selectSQLStatement)

                  

                   } catch DatabaseHelperError.fetchColumnInfo(let message) {

                       throw DatabaseHelperError.querySql(message: message)

                   }

               }

           } else {

               let errmsg: String = String(cString: sqlite3_errmsg(mDB))

               message = "Error: querySQL prepare failed rc: \(returnCode) message: \(errmsg)"

           }

           returnCode = sqlite3_finalize(selectSQLStatement)

           if returnCode != SQLITE_OK {

               let errmsg: String = String(cString: sqlite3_errmsg(mDB))

               message = "Error: querySQL finalize failed rc: \(returnCode) message: \(errmsg)"

           }

           if message.count > 0 {

               throw DatabaseHelperError.querySql(message: message)

           } else {

               return result

           }

       }


class func getColumnValue(index: Int32, type: Int32, stmt: OpaquePointer?) -> Any? {

        if sqlite3_column_type(stmt, index) == SQLITE_NULL {

            return "NULL"

        } else {

            switch type {

            case SQLITE_INTEGER:

                let val = sqlite3_column_int64(stmt, index)

                return Int64(val)

            case SQLITE_FLOAT:

                let val = sqlite3_column_double(stmt, index)

                return Double(val)

            case SQLITE_BLOB:

                let data = sqlite3_column_blob(stmt, index)

                let size = sqlite3_column_bytes(stmt, index)

                let val = NSData(bytes: data, length: Int(size))

                // Convert to string

                let strVal: String = String(decoding: val, as: UTF8.self)

                return strVal

            case SQLITE_TEXT:

                let buffer = sqlite3_column_text(stmt, index)

                var val: String

                if let mBuffer = buffer {

                    val = String(cString: mBuffer)

                } else {

                    val = "NULL"

                }

                return val

            case SQLITE_NULL:

                return "NULL"

            default:

                return "NULL"

            }

        }

    }
```

**Comment by jepiqueau** [comment] 2020-10-29 13:12
@vikashsingh009 Are you using the sqlite plugin inside  an iOS app. UtilsSQLite has no function `fetchColumnInfo1` the function id `fetchColumnInfo` Seems that you are writing your own functions. So i cannot spend time to debug your code. All apps i have written use the plugin from a framework (Angular, React, Vue) for native apps and work fine. If you are using the plugin directly inside an iOS app it is your own code and i cannot help.

**Comment by vikashsingh009** [comment] 2020-10-29 13:34
i  am getting  same  error  even  i  am  using fetchColumnInfo  from util  class also

**Comment by jepiqueau** [comment] 2020-10-29 16:32
@vikashsingh009 the sqlite3 datatypes are
```
NULL
INTEGER
REAL
TEXT
BLOB
``` 
It seems that you are using `VARCHAR` which is not a recognize datatype so it could be the reason.  Try to replace `VARCHAR` with `TEXT` and tell me if it works

**Comment by vikashsingh009** [comment] 2020-10-29 16:47
@jepiqueau ,i  canot  change  the  DataType  for  the  table  as  Table  is  auto  creating  from  api  but  i  have  triyed below  steps
```
case SQLITE_TEXT:

                   guard let queryStatement = try? prepareStatement(mDB:mDB,sql: query) else {

                                  return [["":""]]

                                 }

                                 defer {

                                   sqlite3_finalize(queryStatement)

                                 }

                             

                                 guard sqlite3_step(queryStatement) == SQLITE_ROW else {

                                   return [["":""]]

                                 }

                                 let id = sqlite3_column_int(queryStatement, 0)

                                 guard let queryResultCol1 = sqlite3_column_text(queryStatement, index) else {

                                   print("Query result is nil.")

                                   return [["":""]]

                                 }

                                 let name = String(cString: queryResultCol1) as NSString

                   let buffer = sqlite3_column_text(stmt, index)

                   var val: String

                   if let mBuffer = buffer {

                       val = String(cString: mBuffer)

                   } else {

                    val = name as String

                   }

                   return val


 static func prepareStatement(mDB: OpaquePointer,sql: String) throws -> OpaquePointer? {

     var statement: OpaquePointer?

     guard sqlite3_prepare_v2(mDB, sql, -1, &statement, nil)

         == SQLITE_OK else {

           var  message = "Error: querySQL prepare failed rc: (returnCodmessage:"

       throw DatabaseHelperError.querySql(message: message)

     }

     return statement

    }
```
and  i  am  able  to  get  values  from  Table  ,i  am  not able  to  find  what  was  issues  with earlier  code

**Comment by vikashsingh009** [comment] 2020-10-29 16:49
@jepiqueau ,i  canot  change  the  DataType  for  the  table  as  Table  is  auto  creating  from  api  but  i  have  triyed below  steps
```
case SQLITE_TEXT:

                   guard let queryStatement = try? prepareStatement(mDB:mDB,sql: query) else {

                                  return [["":""]]

                                 }

                                 defer {

                                   sqlite3_finalize(queryStatement)

                                 }

                             

                                 guard sqlite3_step(queryStatement) == SQLITE_ROW else {

                                   return [["":""]]

                                 }

                                 let id = sqlite3_column_int(queryStatement, 0)

                                 guard let queryResultCol1 = sqlite3_column_text(queryStatement, index) else {

                                   print("Query result is nil.")

                                   return [["":""]]

                                 }

                                 let name = String(cString: queryResultCol1) as NSString

                   let buffer = sqlite3_column_text(stmt, index)

                   var val: String

                   if let mBuffer = buffer {

                       val = String(cString: mBuffer)

                   } else {

                    val = name as String

                   }

                   return val


 static func prepareStatement(mDB: OpaquePointer,sql: String) throws -> OpaquePointer? {

     var statement: OpaquePointer?

     guard sqlite3_prepare_v2(mDB, sql, -1, &statement, nil)

         == SQLITE_OK else {

           var  message = "Error: querySQL prepare failed rc: (returnCodmessage:"

       throw DatabaseHelperError.querySql(message: message)

     }

     return statement

    }
```
and  i  am  able  to  get  values  from  Table  ,i  am  not able  to  find  what  was  issues  with earlier  code

**Comment by vikashsingh009** [comment] 2020-10-29 16:50
@jepiqueau ,i  canot  change  the  DataType  for  the  table  as  Table  is  auto  creating  from  api  but  i  have  triyed below  steps
```
case SQLITE_TEXT:

                   guard let queryStatement = try? prepareStatement(mDB:mDB,sql: query) else {

                                  return [["":""]]

                                 }

                                 defer {

                                   sqlite3_finalize(queryStatement)

                                 }

                             
x]

                                 }

                                 let id = sqlite3_column_int(queryStatement, 0)

                                 guard let queryResultCol1 = sqlite3_column_text(queryStatement, index) else {

                                   print("Query result is nil.")

                                   return [["":""]]

                                 }

                                 let name = String(cString: queryResultCol1) as NSString

                   let buffer = sqlite3_column_text(stmt, index)

                   var val: String

                   if let mBuffer = buffer {

                       val = String(cString: mBuffer)

                   } else {

                    val = name as String

                   }

                   return val


 static func prepareStatement(mDB: OpaquePointer,sql: String) throws -> OpaquePointer? {

     var statement: OpaquePointer?

     guard sqlite3_prepare_v2(mDB, sql, -1, &statement, nil)

         == SQLITE_OK else {

           var  message = "Error: querySQL prepare failed rc: (returnCodmessage:"

       throw DatabaseHelperError.querySql(message: message)

     }

     return statement

    }
```
and  i  am  able  to  get  values  from  Table  ,i  am  not able  to  find  what  was  issues  with earlier  code

**Comment by jepiqueau** [comment] 2020-10-29 18:34
@vikashsingh009 I am trying to reproduce the issue#49 by defining name with varchar(255)  and when i do `select * from Users` it works well i will continue a bit deeper

**Comment by jepiqueau** [comment] 2020-10-29 18:56
@vikashsingh009 from my tests issue#49 and issue#50 cannot be reproduced everything works fine. 
my test db is 
```
    BEGIN TRANSACTION;
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        name VARCHAR(255),
        company VARCHAR(255),
        size FLOAT,
        age INTEGER
    );
    CREATE INDEX IF NOT EXISTS users_index_name ON users (name);
    PRAGMA user_version = 1;
    COMMIT TRANSACTION;
```

**Comment by vikashsingh009** [comment] 2020-10-29 19:17
Thanks for your valuable time  ,do we have any sample refrenace where we
are calling getcolumn value and show results it will help me to debug mine
issue if I missed something

**Comment by jepiqueau** [comment] 2020-10-30 06:41
@vikashsingh009 you can look at `https://github.com/jepiqueau/react-sqlite-app-starter` and `Issue49Tests`

**Comment by vikashsingh009** [comment] 2020-10-30 07:01
@jepiqueau thanku  very  much  for  tests provided  ,i  have  implemented  and  tested  and  i  able  to  query  user result.Mine  issues  is  like  all  backend  code  i  have  to   write  in  swift  using Plugin and  Swift  SqlCipher   .I  am  only  getting  issues  when  i  am  calling getColumnValues  from  here  https://github.com/capacitor-community/sqlite/blob/master/ios/Plugin/Utils/UtilsSQLite.swift#L84  ,so  is  any  test  there  in  Swift  where  we  just  passing  SQl  Query  and that  response  back  Query  Results.

**Comment by jepiqueau** [comment] 2020-10-30 08:38
@vikashsingh009 i do not have Swift tests available for this. If you debug step by step  the code with Xcode you may understand the reason for failure and on which field it happens (on a varchar field or on the blob field

**Comment by jepiqueau** [comment] 2020-10-30 08:49
@vikashsingh009 is your Blob a base64 string? otherwise it could be the reason for failure

**Comment by vikashsingh009** [comment] 2020-10-30 09:08
yes,i  have  debug  in  xcode  and  get  to  know  its  failed for varchar as well  Int   for  Varchar  i  am  getting "NULL" and  for  Int  getting  0   but  both  value  did  not  match  according  to  Db  Data.

yes,i  have  blob  base64  encoded

**Comment by jepiqueau** [comment] 2020-10-30 09:14
@vikashsingh009 if your Blob is not a base64 String Can you try this
add a `Blob.swift` file to the plugin
```
public struct Blob {

    public let bytes: [UInt8]

    public init(bytes: [UInt8]) {
        self.bytes = bytes
    }

    public init(bytes: UnsafeRawPointer, length: Int) {
        let i8bufptr = UnsafeBufferPointer(start: bytes.assumingMemoryBound(to: UInt8.self), count: length)
        self.init(bytes: [UInt8](i8bufptr))
    }

}
```
go into `UtilsBinding.swift` and go to the `class func bind` and after line 43 add the following
``` 
        } else if let value = value as? Blob {
            sqlite3_bind_blob(handle, Int32(idx), value.bytes, Int32(value.bytes.count), SQLITETRANSIENT)
```
or 
```
        } else if let value = value as? Blob {
             sqlite3_bind_blob(handle, Int32(idx), [value], Int32(value.count), SQLITETRANSIENT)
```
Tell me if that fix the issue and which one did it or both
If it is the case i will modify the plugin code and publish a new release

**Comment by jepiqueau** [comment] 2020-11-03 06:57
@vikashsingh009 I will close the issue as i did not hear from you since my last comment. I hope that you found what was wrong in your side as all the tests i did from my side did not show any errors

**Closed by jepiqueau** 2020-11-03 06:57 UTC
