### ISSUE TITLE
runTest failed Error: Attempt to invoke virtual method 'java.lang.String com.getcapacitor.community.database.sqlite.CapacitorSQLite.echo(java.lang.String)' on a null object reference`

### ISSUE THREAD

**Issue by ASHBAW** [capacitor-community/sqlite#224] opened 2022-02-17 21:21 UTC
I have an Ionic 6 application using Angular (13). 

I followed the steps in the documentation:

1) Created a sqlite.service.ts and copied in the service provided.
2) Added service to my app.module.ts as a provider.
3) Added the following into app.component.ts

```
initializeApp() {
    this.platform.ready().then(async () => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();
      this._sqlite.initializePlugin().then(ret => {
        this.initPlugin = ret;
        console.log('>>>> in App  this.initPlugin ' + this.initPlugin);
      });
    });
```
which returns the following when launching the app:
`>>>> in App  this.initPlugin true`

In my page I have the following:

```
constructor(private translate: TranslateService,
              private sqlite: SQLiteService) { }

async ngOnInit(): Promise<void> {
    try {
      await this.runTest();
    } catch (err) {
      console.log(`$$$ runTest failed ${err.message}`);
    }
  }

async runTest(): Promise<void> {
    try {
      let result: any = await this.sqlite.echo("Hello World");
      console.log(" from Echo " + result.value);

      // ************************************************
      // Create Database No Encryption
      // ************************************************

      // initialize the connection
      let db = await this.sqlite
                  .createConnection("testEncryption", false, "no-encryption", 1);

      // open db testEncryption
      await db.open();

      await this.sqlite.closeConnection("testEncryption"); 

      return Promise.resolve();

    } catch (err) {
      return Promise.reject(err);
    }
  }
```

When I go to the page I am getting the following error:

``$$$ runTest failed Error: Attempt to invoke virtual method 'java.lang.String com.getcapacitor.community.database.sqlite.CapacitorSQLite.echo(java.lang.String)' on a null object reference`
`

Any insight as to what I am doing wrong?

**Comment by jepiqueau** [comment] 2022-02-18 07:01
@ASHBAW it seems that sqlite is not defined can you share your app on github.com so i can have a look

**Comment by mpizarroc** [comment] 2022-02-18 20:41
Hi all,

i have similar error and previously this was working without problem.

Error: Error: Error: isDatabase: Attempt to invoke virtual method 'java.lang.Boolean com.getcapacitor.community.database.sqlite.CapacitorSQLite.isDatabase(java.lang.String)' on a null object reference

Any idea of the error?

**Comment by ASHBAW** [comment] 2022-02-18 21:31
Unfortunately my manager will not allow me to share our app. I was able to track it down and am not sure as to why it is effecting it.

First this issue is only on Android. iOS works great.

I created a new simple ionic angular project and run  the code in runTest() above. At that point I started adding our code to the new project to see when it would break. I was able to add our code without issue. I then copied all the node_modules in with no issue. Finally I copied in the android directory and was able to trace it down to the versionCode in the build.gradle 

```
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "com.my.appr"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.2.7"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        aaptOptions {
             // Files and dirs to omit from the packaged assets dir, modified to accommodate modern web apps.
             // Default: https://android.googlesource.com/platform/frameworks/base/+/282e181b58cf72b6ca770dc7ca5f91f135444502/tools/aapt/AaptAssets.cpp#61
            ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
        }
    }
```
If I chose a large number for example our version code is 100073 I get the null error. If I change it to like 1, 2, etc. It works fine.

I am completely baffled as to why they would effect it?

**Comment by jepiqueau** [comment] 2022-02-19 07:53
@mpizarroc no you have to share your code or 
a small  replicated app showing the issue. What you may be doing is to remove the Android folder and then run
npm run build
npx cap add android
npx cap sync
npm run build
npx cap copy
npx cap open Android
This may help

**Comment by jepiqueau** [comment] 2022-02-19 07:55
@ASHBAW  well it seems that is nothing to do with the use of the plugin but a versionning issue in Android gradle file. I do not know what is the maximum code version is

**Comment by jepiqueau** [comment] 2022-02-19 08:00
@ASHBAW  it seems to be 2100000000 after some googling so it should not be the reason

**Comment by jepiqueau** [comment] 2022-02-19 08:17
@ASHBAW as this happen on the echo command it is the setup of the  sqlite plugin whic is not done properly. So you can create a small app which just your setup till you get to the  call of the echo method there is no needs to put any of the database confidential data.this is the reason for having this method. Otherwise you can do the same procédure given to @mpizarroc  above they could be some cache issues. Having said thzt i cannât do more

**Comment by ASHBAW** [comment] 2022-02-21 17:29
Thanks for the response. And yeah I am not sure why changing things in the Android build.gradle would have an effect on this plugin. And I understand I do not need to put any of the database confidential data. I was just copying/pasting out of the provided test case.

I tried creating  a new project from scratch but once I starting changing the build.gradle it gives me the error. I then started setting breakpoints in the plugin, in Android Studio. It fails on the **EncryptedSharedPreferences.create()** in **CapacitorSQLite()**:

```
    public CapacitorSQLite(Context context) throws Exception {
        this.context = context;
        try {
            // create or retrieve masterkey from Android keystore
            // it will be used to encrypt the passphrase for a database
            MasterKey masterKeyAlias = new MasterKey.Builder(context).setKeyScheme(MasterKey.KeyScheme.AES256_GCM).build();
            // get instance of the EncryptedSharedPreferences class
            this.sharedPreferences =
                EncryptedSharedPreferences.create(
                    context,
                    "sqlite_encrypted_shared_prefs",
                    masterKeyAlias,
                    EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
                    EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
                );
            this.uSecret = new UtilsSecret(this.context, this.sharedPreferences);
        } catch (Exception e) {
            throw new Exception(e.getMessage());
        }
```
Prior to error:
![Screen Shot 2022-02-21 at 11 14 38 AM](https://user-images.githubusercontent.com/8959369/155002872-bc0c1d11-5471-4821-bb13-808dd9b504cf.png)

The error it returns is:
![Screen Shot 2022-02-21 at 11 15 18 AM](https://user-images.githubusercontent.com/8959369/155002274-b1ececfa-323d-4cdd-aac9-0685929e1ec8.png)

If I make the change in the Android build.gradle it works and I do not get this error.

Can you think of anything I could look at/debug to get more information?

Thanks

**Comment by ASHBAW** [comment] 2022-02-21 18:11
I created a simple ionic 6 project that demonstrates the issue.

https://gitlab.com/BAW/sqlite3

Steps in project creation:

1. ionic start sqlite
2. ionic cap add android
3. went into Android build.gradle and changed parameters there (applicationId, versionCode, versionName)
4. added changes to home.page.ts
5. added sqlite.service.ts provided by your repository
4. npm install 
5. ionic cap sync
6. ionic cap build
7. run app
8. app displays page with button
9. button push makes sqlite echo call
10. see null error

**Comment by ASHBAW** [comment] 2022-02-21 18:58
Looks like in your build.gradle you are using this alpha version:

   implementation "androidx.security:security-crypto:1.1.0-alpha03"

See these links for related issue:

https://github.com/google/tink/issues/504
https://issuetracker.google.com/issues/158234058?pli=1#comment48
https://github.com/google/tink/issues/413

**Comment by jepiqueau** [comment] 2022-02-23 12:45
@ASHBAW i just clone your project  and do
```
npm install
npm run build
npx cap sync
npm run build
npx cap copy
npx cap open android
```
in android studio
```
Clean Project
Android Studio -> Preferences -> Build, Execution, Deployment -> Build Tools->Gradle and set the gradle JDK to 11 version 11.0.10 it was on 16 Amazon Coretto 16.0.2
Sync Project with Gradle Files
Rebuild the Project
and Run it on the Emulator Pixel 3a XL API30
```
and it works fine 

```
2022-02-23 13:20:29.722 2537-2590/com.lesterelectrical.chargerconnect.lester D/Capacitor: Handling local request: http://localhost/main.js
2022-02-23 13:20:31.402 2537-2537/com.lesterelectrical.chargerconnect.lester I/Capacitor/Console: File: http://localhost/vendor.js - Line 1371 - Msg: Ionic Native: deviceready event fired after 74 ms
2022-02-23 13:20:31.753 2537-2537/com.lesterelectrical.chargerconnect.lester I/Capacitor/Console: File: http://localhost/vendor.js - Line 99895 - Msg: Angular is running in development mode. Call enableProdMode() to enable production mode.
2022-02-23 13:20:31.760 2537-2593/com.lesterelectrical.chargerconnect.lester D/Capacitor: Handling local request: http://localhost/common.js
2022-02-23 13:20:31.767 2537-2599/com.lesterelectrical.chargerconnect.lester D/Capacitor: Handling local request: http://localhost/node_modules_ionic_core_dist_esm_ion-app_8_entry_js.js
2022-02-23 13:20:31.803 2537-2593/com.lesterelectrical.chargerconnect.lester D/Capacitor: Handling local request: http://localhost/src_app_home_home_module_ts.js
2022-02-23 13:20:31.811 2537-2537/com.lesterelectrical.chargerconnect.lester W/Capacitor/Console: File: http://localhost/vendor.js - Line 1677 - Msg: Native: tried calling StatusBar.styleDefault, but the StatusBar plugin is not installed.
2022-02-23 13:20:31.813 2537-2537/com.lesterelectrical.chargerconnect.lester W/Capacitor/Console: File: http://localhost/vendor.js - Line 1683 - Msg: Install the StatusBar plugin: 'ionic cordova plugin add cordova-plugin-statusbar'
2022-02-23 13:20:31.814 2537-2537/com.lesterelectrical.chargerconnect.lester W/Capacitor/Console: File: http://localhost/vendor.js - Line 1677 - Msg: Native: tried calling SplashScreen.hide, but the SplashScreen plugin is not installed.
2022-02-23 13:20:31.815 2537-2537/com.lesterelectrical.chargerconnect.lester W/Capacitor/Console: File: http://localhost/vendor.js - Line 1683 - Msg: Install the SplashScreen plugin: 'ionic cordova plugin add cordova-plugin-splashscreen'
2022-02-23 13:20:31.818 2537-2537/com.lesterelectrical.chargerconnect.lester I/Capacitor/Console: File: http://localhost/main.js - Line 87 - Msg: >>>> in App  this.initPlugin true
2022-02-23 13:20:32.007 2537-2593/com.lesterelectrical.chargerconnect.lester D/Capacitor: Handling local request: http://localhost/node_modules_ionic_core_dist_esm_ion-button_2_entry_js.js
2022-02-23 13:20:32.026 2537-2599/com.lesterelectrical.chargerconnect.lester D/Capacitor: Handling local request: http://localhost/node_modules_ionic_core_dist_esm_swipe-back-b60369d0_js.js
2022-02-23 13:20:32.083 2537-2593/com.lesterelectrical.chargerconnect.lester D/Capacitor: Handling local request: http://localhost/node_modules_ionic_core_dist_esm_ion-ripple-effect_entry_js.js
2022-02-23 13:20:32.101 2537-2602/com.lesterelectrical.chargerconnect.lester D/Capacitor: Handling local request: http://localhost/assets/icon/favicon.png
2022-02-23 13:20:32.175 2537-2593/com.lesterelectrical.chargerconnect.lester D/Capacitor: Handling local request: http://localhost/node_modules_ionic_core_dist_esm_tap-click-a895802b_js.js
2022-02-23 13:20:32.175 2537-2602/com.lesterelectrical.chargerconnect.lester D/Capacitor: Handling local request: http://localhost/node_modules_ionic_core_dist_esm_status-tap-c10ad309_js.js
2022-02-23 13:20:32.197 2537-2637/com.lesterelectrical.chargerconnect.lester V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 132522771, pluginId: App, methodName: addListener
2022-02-23 13:20:32.206 2537-2637/com.lesterelectrical.chargerconnect.lester V/Capacitor: callback: 132522771, pluginId: App, methodName: addListener, methodData: {"eventName":"backButton"}
2022-02-23 13:21:26.864 2537-2537/com.lesterelectrical.chargerconnect.lester I/Capacitor/Console: File: http://localhost/src_app_home_home_module_ts.js - Line 132 - Msg: >>>> I Clicked HERE <<<<
2022-02-23 13:21:26.873 2537-2637/com.lesterelectrical.chargerconnect.lester V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 132522772, pluginId: CapacitorSQLite, methodName: echo
2022-02-23 13:21:26.874 2537-2637/com.lesterelectrical.chargerconnect.lester V/Capacitor: callback: 132522772, pluginId: CapacitorSQLite, methodName: echo, methodData: {"value":"Hello World"}
2022-02-23 13:21:26.902 2537-2537/com.lesterelectrical.chargerconnect.lester I/Capacitor/Console: File: http://localhost/src_app_home_home_module_ts.js - Line 113 - Msg: >>>> from Echo Hello World <<<<
2022-02-23 13:21:26.912 2537-2637/com.lesterelectrical.chargerconnect.lester V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 132522773, pluginId: CapacitorSQLite, methodName: createConnection
2022-02-23 13:21:26.912 2537-2637/com.lesterelectrical.chargerconnect.lester V/Capacitor: callback: 132522773, pluginId: CapacitorSQLite, methodName: createConnection, methodData: {"database":"testEncryption","encrypted":false,"mode":"no-encryption","version":1}
2022-02-23 13:21:26.995 2537-2614/com.lesterelectrical.chargerconnect.lester V/com.getcapacitor.community.database.sqlite.SQLite.Database: &&& file path /data/user/0/com.lesterelectrical.chargerconnect.lester/databases/testEncryptionSQLite.db
2022-02-23 13:21:27.165 2537-2637/com.lesterelectrical.chargerconnect.lester V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 132522774, pluginId: CapacitorSQLite, methodName: open
2022-02-23 13:21:27.165 2537-2637/com.lesterelectrical.chargerconnect.lester V/Capacitor: callback: 132522774, pluginId: CapacitorSQLite, methodName: open, methodData: {"database":"testEncryption"}
2022-02-23 13:21:27.297 2537-2537/com.lesterelectrical.chargerconnect.lester I/Capacitor/Console: File: http://localhost/ - Line 204 - Msg: undefined
2022-02-23 13:21:27.340 2537-2537/com.lesterelectrical.chargerconnect.lester I/Capacitor/Console: File: http://localhost/ - Line 204 - Msg: undefined
2022-02-23 13:21:27.349 2537-2637/com.lesterelectrical.chargerconnect.lester V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 132522775, pluginId: CapacitorSQLite, methodName: closeConnection
2022-02-23 13:21:27.349 2537-2637/com.lesterelectrical.chargerconnect.lester V/Capacitor: callback: 132522775, pluginId: CapacitorSQLite, methodName: closeConnection, methodData: {"database":"testEncryption"}
2022-02-23 13:21:27.379 2537-2537/com.lesterelectrical.chargerconnect.lester I/Capacitor/Console: File: http://localhost/ - Line 204 - Msg: undefined

```
i saw that you set the applicationId "com.lesterelectrical.chargerconnect.lester" in your gradle file i think it would be better to set it up in the appId of the  capacitor.config.ts file  prior to do a `npx cap add android` so the manifest file will be correct which is not the case now as  `package="io.ionic.starter">` it should be `package="com.lesterelectrical.chargerconnect.lester">`

so from this i do not know what to do as it works for me

**Comment by jepiqueau** [comment] 2022-02-23 12:50
@ASHBAW Tell me if you finally succeed to make it working

**Comment by jepiqueau** [comment] 2022-02-23 13:55
@mpizarroc is it working now on your side

**Comment by ASHBAW** [comment] 2022-02-23 14:19
Thanks for looking. 

I ran through your steps. Not sure why you saw 16 Amazon Coretto 16.0.2. I do not have that installed. It has always been set to 11 version 11.0.10. See figure.

![Screen Shot 2022-02-23 at 8 02 53 AM](https://user-images.githubusercontent.com/8959369/155334990-90d14739-e067-4d8c-93cb-89e58cc45407.png)

I did change the package name in the manifest file to match - package="com.lesterelectrical.chargerconnect.lester"

I still get the null error

![Screen Shot 2022-02-23 at 8 05 20 AM](https://user-images.githubusercontent.com/8959369/155335154-c56fb97d-d2e8-4fbc-869f-1860911d7004.png)

I really think it has something to do with the "androidx.security:security-crypto:1.1.0-alpha03" package. If I set a breakpoint in your plugin I get this exact error:

https://github.com/google/tink/issues/504

**Comment by jepiqueau** [comment] 2022-02-23 14:58
@ASHBAW i do not know as i am not getting the error and i left the  versionCode and versionName to what you set-up.

**Comment by ASHBAW** [comment] 2022-02-23 15:04
Every device I have tested this new version of the app on, I had a previous version of the app installed. 

Previous versions of the app did not use your plugin (just added it for this recent version) and had a versionCode of 100072 and below tied to that applicationId. So if I set the versionCode to a number less than that it works. A newer version code does not when tied to that applicationId. 

It is like the Android device is retaining something even though I uninstall the app and install a newer version.

I bet if I tried installing the app on a device that never had the app installed before it would work with the higher versionCode number tied to the applicationId.

**Comment by ASHBAW** [comment] 2022-02-23 15:06
Of course that does not help because our current users would already have the app installed on their device.

**Comment by jepiqueau** [comment] 2022-03-01 11:57
@ASHBAW Did you find the solution?

**Comment by ASHBAW** [comment] 2022-03-01 13:58
I unfortunately did not. 

If I ran that simple test case that worked for you and did not for me on a new device that never had an app installed with com.lesterelectrical.chargerconnect.lester as the applicationId it would work. If I tried running the simple test application on a device that previously had our app which has com.lesterelectrical.chargerconnect.lester as the applicationId it would give me the error. 

Stepping through the code it is failing on EncryptedSharedPreferences.create() in CapacitorSQLite() where EncryptedSharedPreferences.create() is tied to the androidx.security:security-crypto:1.1.0-alpha03 package. 

In the end I had to remove the plugin and go with another one.

**Comment by jepiqueau** [comment] 2022-03-02 07:15
@ASHBAW i am sorry to hear that but as i cannât reproduce the error it is difficult for me to look for a fix. Did you try to remove the sqlite_encrypted_shared_prefs.xml file from the shared_pref folder of your app and restart. Is your app use encrypted databases?. By the which other plugin are you using? It is clearing that i should not have move to the alpha version but developpers where asking to have the plugin working with minSdkVersion 21 which is not the case with the androidx.security:security-crypto:1.0.0 and at that time i touche that Google will move quickly to 1.1.0 which is not the case

**Comment by ASHBAW** [comment] 2022-03-02 13:05
Yeah, I understand. If you cannot reproduce it, you cannot fix it. I will try removing the .xml to see if that helps. We do not use encrypted databases. I ended up using the cordova plugin https://github.com/storesafe/cordova-sqlite-storage.

I appreciate your response and looking into this.

**Comment by fasterlars** [comment] 2022-03-02 20:34
Just wanted to say that I had a similar problem with a vue app using capacitor and sqlite. 
We´ve been bumping the build number for every release, but when we reached _versionCode 35_, the` 'java.lang.String com.getcapacitor.community.database.sqlite.CapacitorSQLite.echo(java.lang.String)' on a null object reference`` error began to arise. This took hours to find out 😅
Without going further into details about the reason, my solution is just to bump the minor version number, and reset the versionCode to 1.

**Comment by ASHBAW** [comment] 2022-03-02 20:42
Yeah that is what I was seeing. Thanks for posting your work around.

**Comment by fasterlars** [comment] 2022-03-03 09:51
> Just wanted to say that I had a similar problem with a vue app using capacitor and sqlite. We´ve been bumping the build number for every release, but when we reached versionCode 34, the `java.lang.String com.getcapacitor.community.database.sqlite.CapacitorSQLite.echo(java.lang.String) on a null object reference` error began to arise. This took hours to find out 😅 Without going further into details about the reason, my solution is just to bump the minor version number, and reset the versionCode to 1.

Found out that this is not a workaround since the android play store doesn't allow resetting the build number. It has to be incremental. So I´m pretty much screwed now, and have to dive deeper into the problem.
Guess you haven´t found a solution yet?

**Comment by jepiqueau** [comment] 2022-03-03 11:54
@fasterlars i am looking at it but did not find a fix yet are you using database encryption?

**Comment by fasterlars** [comment] 2022-03-03 12:04
> @fasterlars i am looking at it but did not find a fix yet are you using database encryption?

No I am not using database encryption.
I had my colleague to build an apk. He is on a mac with an Android Studio installation, sdk and so on, that probably differs from my setup. And that apk seems to work. So right now I am looking into re-install Android Studio, tools and SDK´s.

**Comment by fasterlars** [comment] 2022-03-03 13:13
Update:
After a complete reinstallation of Android Studio and SDK´s the problem seems to be gone. I can build apk´s with build numbers higher than 34, and the sqlite database connection now works fine.
Unfortunately I have not become any wiser regarding the root of the problem.

**Comment by jepiqueau** [comment] 2022-03-03 13:36
@fasterlars For me it is really strange i had the issue i tried to debug without success except that the error was From the keyStore User not authorized and getting the error the master key android-keystore://_androidx_security_master_key_ exists but is unusable. After this i move down the version lower than 34 in the gradle run it works and increase again the version to 100035 and it still works. and now whatever i do i cannot get the error back

**Comment by jepiqueau** [comment] 2022-03-03 13:40
@fasterlars which version of Android Studio are you running?

**Comment by fasterlars** [comment] 2022-03-03 19:38
> @fasterlars which version of Android Studio are you running?

Well right now I am using the latest version of Android Studio (Bumble bee). Before that I was using Arctic Fox, but I really cant remember precicely what version or which SDK´s I was using when I had the error. And didn´t took note of it - sorry.

**Comment by jepiqueau** [comment] 2022-03-04 18:05
@ASHBAW @fasterlars In release 3.4.1-1, for developers not using database encryption i add two parameters ` iosIsEncryption` & `androidIsEncryption` in the `capacitor.config.ts` when set to false the `KeyChain iOs` and the `MasterKey Android` will not be set. This should normally solve that issue. Look at angular-sqlite-app-starter@3.4.1-1

```
  plugins: {
    CapacitorSQLite: {
      iosDatabaseLocation: 'Library/CapacitorDatabase',
      iosIsEncryption: false,
      androidIsEncryption: false,
    }
```
Hope this will help

**Comment by ASHBAW** [comment] 2022-03-04 18:18
Great thank you!

**Comment by jepiqueau** [comment] 2022-03-04 19:39
@ASHBAW @fasterlars i close the issue then

**Closed by jepiqueau** 2022-03-04 19:39 UTC

**Comment by fasterlars** [comment] 2022-03-10 13:24
I just want to add that this problem suddently became present again for me. But only on an Oneplus Android version 11 device. Ive tried other Samsung and Huawei devices, both version 10 and 11. But not a problem om those.
The `androidIsEncryption: false` fix solved the problem on the Oneplus device. 
Thanks alot!
