### ISSUE TITLE
Encrypted Database isn't Encrypted

### ISSUE THREAD

**Issue by KevinTurnbull** [capacitor-community/sqlite#375] opened 2023-02-04 16:31 UTC
**Describe the bug**
One of the features I need for an application I'm building is Data-at-Rest encryption. It appears that the encryption feature of this plugin doesn't work for creating SQLite database files that are encrypted in storage.

**To Reproduce**

Install the test app as normal:
1. `git clone https://github.com/jepiqueau/angular-sqlite-app-starter.git`
2. `npm install`
3. `ionic cap sync`
4. `npx cap update`

Edit app to not delete the test database after test and create a rooted emulator:
1. Edit file `angular-sqlite-app-starter/src/app/test/testencryption/testencryption.page.ts` to comment out line 154 (`await deleteDatabase(db);`)
2. Start an android API 31 debug build emulator
3. `adb root`

Run the Encryption test page and download the database file
1. `ionic cap run android`
2. Load the Test Encryption page
3. `adb pull /data/data/com.jeep.app.ionic.angular/databases/testEncryptionSQLite.db`

The bug is that `testEncryptionSQLite.db` is an unencrypted database representing the data stored during the course of the encryption test.

**Expected behavior**
The file pulled from the emulator should be encrypted using the default passphrase.

**Smartphone (please complete the following information):**

- Device: Android Pixel 2 Emulator running API 31 (rooted)

**Comment by KevinTurnbull** [comment] 2023-02-05 14:12
With some code digging I've found out how to do the encryption process properly. 

Long story short; you have to make a non-encrypted database first, open a connection to that database (which makes the actual database file), then close the connection, then make an "encryption" mode connection, open the connection (which does the actual encryption of the currently empty database) to that database, then close it, then finally opening the database in "secret" mode. If you don't close the connection between steps then the old database connection will be reused instead of respecting the new requested mode.

**Comment by jepiqueau** [comment] 2023-02-08 07:51
@KevinTurnbull this procedure is shown in https://github.com/,jepiqueau/angular-sqlite-app-starter/src/app/test/testencryption/testencryption.page.ts
For a direct encryption of a database look at test2dbs/test2dbs.page.ts for database testSet

**Comment by jepiqueau** [comment] 2023-02-09 08:43
@KevinTurnbull is this now fixed. If yes canyou close the issue

**Comment by jepiqueau** [comment] 2023-02-15 12:49
@KevinTurnbull as you did not follow-up i assume that is fixed so i close the issue

**Comment by KevinTurnbull** [comment] 2023-02-15 12:50
The problem still exists as described.

**Comment by jepiqueau** [comment] 2023-02-15 15:33
@KevinTurnbull if so show me your code. Did you try the test2dbs in angular-sqlite-app-starter which is working so look at the différence to your code

**Comment by jepiqueau** [comment] 2023-02-15 16:17
@KevinTurnbull What do you mean by `Start an android API 31 debug build emulator` and how you do it

**Comment by jepiqueau** [comment] 2023-02-15 17:10
@KevinTurnbull i did follow the Reproduce process and it works fine with the database 'testEncryptionSQLite.db' encrypted.
May be you did not set the encryption passphrase before loading the Test Encryption page.

**Comment by KevinTurnbull** [comment] 2023-02-15 17:14
I suspect you might be using an emulator that had a previous install of the app. The key point of the bug is that strictly following the encryption process by using the example produces a non-encrypted database. 

Don't take this the wrong way; what you've created is great and a huge benefit to the community. It is just slightly unclear instructions and an example that doesn't create the result as described (although it appears to if one doesn't dig under the hood).

**Comment by jepiqueau** [comment] 2023-02-15 17:16
@KevinTurnbull i am not taking the wrong way i just want to reproduce what you had to solve it. ok i am going to delete the app from the emulator an redo the process

**Comment by jepiqueau** [comment] 2023-02-15 17:54
@KevinTurnbull Can you give me the command line for ` Start an android API 31 debug build emulator` on a mac. i am not use to that process i never use adb but use npx cap open android for testing.
When i do this it never end so i cannot do adb root
```
Users/queaujeanpierre/Library/Android/sdk/emulator/emulator -avd Pixel_5_API_32 -netdelay none -netspeed full
```

**Comment by KevinTurnbull** [comment] 2023-02-15 18:26
I didn't do it from the command line. I did it using Android studio.

Using the device manager.

**Comment by jepiqueau** [comment] 2023-02-15 19:31
@KevinTurnbull Ok i reproduce it and the reason is what i said you didn't load the page 'Test Set Secure Secret' first before to load the page 'Test Encryption' meaning that you do not have a passphrase stored. I will have to test against this. thanks for your contribution so i reopen the issue for a reminder as a TODO

**Comment by KevinTurnbull** [comment] 2023-02-15 19:33
Good catch. I had already worked around the problem in my own project so there's no urgency from my side. Thanks for the great work you do!

**Closed** 2023-02-15 21:31 UTC
