### ISSUE TITLE
Unhandled Error Error: SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by ogadepoju** [capacitor-community/sqlite#211] opened 2022-01-05 13:27 UTC
**Describe the bug**
@jepiqueau 
Many thanks for your consistent help regarding @capacitor-community/sqlite.
but working on a project using @capacitor-community/sqlite which works fine on a developer PC but on installing the app on a different computer, it raised an error when I tried to access/create a database.

![Capture](https://user-images.githubusercontent.com/38212389/148225030-7b41140d-89bf-440d-a6f4-a66a2c910d93.PNG)

**Comment by jepiqueau** [comment] 2022-01-05 17:45
@ogadepoju  @IT-MikeS Sorry, i am not looking at the electron platform before a more stable release of the @capacitor- community/electron is published on npm.

**Comment by ogadepoju** [comment] 2022-01-06 08:15
@jepiqueau  thanks for your response but for urgency sake can you help with this, it has gotten me stocked for weeks, 
It's working perfectly of my machine, but once installed on another machine it pop this error.
Thanks.

**Comment by jepiqueau** [comment] 2022-01-08 17:36
@ogadepoju i made a testing release of the `@capacitor-community/sqlite` 
Can you do 
```bash
npm install -save-dev @capacitor-community/sqlite@3.3.3-test211
npx cap sync @capacitor-community/electron
npm run build
npx cap copy @capacitor-community/electron
```
and the you create your executable and run it on another PC

the databases will now be under the
`YOUR_APPLICATION/electron/CapacitorDatabases` folder.

Tell me if that solve your issue and then i will make a fix

**Comment by jepiqueau** [comment] 2022-01-10 17:27
@ogadepoju any news?

**Comment by jepiqueau** [comment] 2022-01-11 12:27
@ogadepoju i worked hard as you said it was urgent but since then you did not tell me if it helps. Can you please revert to me

**Comment by ogadepoju** [comment] 2022-01-11 14:05
@jepiqueau thanks for your response and i'm sorry for my slow/delayed response, i tried the solution provided but it doesn't solve the issue,
But when i do "INSTALL FOR SELF", it opened.

Thanks

**Comment by jepiqueau** [comment] 2022-01-11 17:10
@ogadepoju what do you mean by ' do "INSTALL FOR SELF" '

**Comment by jepiqueau** [comment] 2022-01-13 07:56
@ogadepoju Can you please answer and tell me if it works so i can release it and close the issue. I cannot test it myself as my windows platform is out of order.

**Comment by pkzOR** [comment] 2022-03-14 20:58
With Electron, if you install for "anyone...", then the app needs to be run as ADMIN to work. This is because the db is put in the Program Files folder. Install "only for me" puts the db in   C:\Users\<USER>\AppData\Local\Programs\<AppNAME> folder, not where expected (C:\Users\<USER>\Databases\<AppName>. Both install scenarios seem wrong. 

Is this a bug for this plugin???

**Comment by jepiqueau** [comment] 2022-03-15 07:14
@pkzOR i will have a look again. This is a old question and i could not find a solution as i though it was due to @capacitor-community/electron. Where do you want the database to be located?

**Comment by jepiqueau** [comment] 2022-03-15 07:16
@ogadepoju did you find a solution yourself that you can share on this issue

**Comment by jepiqueau** [comment] 2022-03-15 08:06
@pkzOR When you install for anyone in a computer (assuming Windows), do you want everyone to access the same databases or do you want them to access their own (C:\Users<USER>\Databases<AppName>)?

**Comment by pkzOR** [comment] 2022-03-15 15:44
@jepiqueau  For my use case, installing for everyone  I would want  each user to have their own db. However, I can imagine other use cases where all users need tp access the same db.

Perhaps your API can allow both  DRIVE/PATH,  and Well Known Windows paths (like Documents, ProgramData, etc)?  So, when creating the db with an Drive and Path, the install for everyone or all users would  then have a single db.  When createing a db with a well know path (like ProgramData), the install for everyone or all users  would then have a db for each user.  I think this would allow for both install scenarios.

The convention of C:\Users\Databases is not a necessity, it was just an expection from the documentation.

**Comment by pkzOR** [comment] 2022-03-17 18:49
@jepiqueau  Thanks so much for your work! 

(Note: the readme says "config.config.ts", but I'm sure you meant "capacitor.config.ts".

Locally, we build/run on Windows with occasional checking on the MacBook, but our CI/CD pipeline will be MacOs.  It will be a week or so before we get all the build steps working and can test the final deployment. So, I'll let you know if we discover anything. 

Thanks again.

**Comment by jepiqueau** [comment] 2022-03-17 18:58
@pkzOR yes it is a typo error. I will be out for the next five days.

**Comment by pkzOR** [comment] 2022-03-24 15:57
@jepiqueau  Sorry, but no progress as other priorties crept in this week.

**Comment by pkzOR** [comment] 2022-03-24 15:57
@jepiqueau  Sorry, but no progress as other priorties crept in this week.

**Comment by pkzOR** [comment] 2022-03-30 15:42
@jepiqueau  I've confirmed that under Electron, the db is created in the expected location. It will be awhile before iOS and Android builds are running in our build environment, so for now, I consider this issue as being resolved.

Thanks for you efforts.

**Comment by jepiqueau** [comment] 2022-03-31 05:39
@pkzOR OK thanks so i will close the issue from now on. Feel free to re-open it if require. Good luck with your development

**Closed** 2022-03-31 05:39 UTC
