### ISSUE TITLE
Database fails to open when browser window minimized

### ISSUE THREAD

**Issue by michaelgoeke** [capacitor-community/sqlite#402] opened 2023-04-21 17:15 UTC
**Describe the bug**
Error: >>> jeep-sqlite StoreName: undefined is not opened
    at CapacitorSQLiteWeb.checkConnectionsConsistency (web.ts:151:13)
    at async SQLiteConnection.checkConnectionsConsistency (definitions.ts:1350:9)

I've run into intermittent failures in playwright tests of my application.
It seems sometimes the sqlite initialization fails.
It looks like the playwright test failures may have to do with performance issues and system resources.
I suspect it has something to do with leaning on a stencil element for the web version instead of a plain library.

However I noticed the problem reproduces inconsistently outside of running playwright, and then found it happens every time if I minimize the browser window with devtools open, then cause the page to reload.

In the main.ts file for my app, we set up jeep-sqlite if we're on platform 'web', then initialize the db connection.

```ts 
 customElements.define('jeep-sqlite', JeepSqlite);

    window.addEventListener('DOMContentLoaded', async () => {
      const jeepSqliteElement = document.createElement('jeep-sqlite');
      document.body.appendChild(jeepSqliteElement);
      await customElements.whenDefined('jeep-sqlite');
      await commonInit();
        //commonInit is where _sqliteConnection.initWebStore() and _sqliteConnection.checkConnectionsConsistency() are called
```

**To Reproduce**
given an application with initialization of the database connection in main.ts
1. open dev tools
2. minimize main browser window
3. cause page to reload (reload in dev tools, cause HMR if running `serve` 
4. see error message
Error: >>> jeep-sqlite StoreName: undefined is not opened
    at CapacitorSQLiteWeb.checkConnectionsConsistency (web.ts:151:13)
    at async SQLiteConnection.checkConnectionsConsistency (definitions.ts:1350:9)

**Expected behavior**
database connection able to be established. checkConnectionsConsistency should not fail with 'undefined is not opened' message.

**Screenshots**
n/a

**Desktop (please complete the following information):**

- OS: Windows
- Browser chrome
- Version 112

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a
Ask if more details are needed.
I'm using capacitor 4.7.1. jeep-sqlite 2.2.3, capacitor-community/sqlite 4.6.0.
Web framework is vue 3.

**Comment by jepiqueau** [comment] 2023-04-22 06:43
@michaelgoeke in the commonInit do you have 
await _sqliteConnection.initWebStore as it seems that it is doing the checkConnectionConsistency before the initWebStore is ended.

**Comment by michaelgoeke** [comment] 2023-04-24 16:31
I added logging around `initWebStore` and `checkConnectionsConsistency`
still seems to be failing

console log:
``` ts
SqliteService.ts:25 calling _sqliteConnection.initWebStore()
SqliteService.ts:28 finished calling _sqliteConnection.initWebStore()
SqliteService.ts:31 calling _sqliteConnection.checkConnectionsConsistency()
web.ts:144 in web checkConnectionsConsistency: {"dbNames":[],"openModes":[]}
Error: >>> jeep-sqlite StoreName: undefined is not opened
    at CapacitorSQLiteWeb.checkConnectionsConsistency (web.ts:151:13)
    at async SQLiteConnection.checkConnectionsConsistency (definitions.ts:1350:9)
    at async SqliteService.init (SqliteService.ts:32:5)
    at async commonInit (main.ts:53:3)
    at async main.ts:44:7 undefined window.unhandledrejection error in promise() 
```

**Comment by michaelgoeke** [comment] 2023-04-24 16:37
In case it was some sort of race condition, I tried adding a 10 second await after the `initWebStore()` call, before the `checkConnectionsConsistency()` call.

Same results. Succeeds if window is not minimized, fails if it is minimized.

**Comment by michaelgoeke** [comment] 2023-04-24 16:42
The call to `_sqliteConnection.createConnection` was after initWebStore and checkConnectionsConsistency.
When I moved the checkConnectionsConsistency call to be after, then the error occurs on db.open();

the message is:

``` ts
SqliteService.ts:27 calling _sqliteConnection.initWebStore()
SqliteService.ts:30 finished calling _sqliteConnection.initWebStore()
Error: WebStore is not open yet. You have to call "initWebStore()" first.
    at CapacitorSQLiteWeb.ensureWebstoreIsOpen (web.ts:454:13)
    at CapacitorSQLiteWeb.createConnection (web.ts:91:10)
    at runtime.js:95:35
    at async SQLiteConnection.createConnection (definitions.ts:1196:7)
    at async SqliteService.init (SqliteService.ts:39:16)
    at async commonInit (main.ts:53:3)
    at async main.ts:44:7 undefined window.unhandledrejection error in promise() 
```

**Comment by jepiqueau** [comment] 2023-05-09 12:26
@michaelgoeke You must provide the commonInit() method so it will be clear how you call the init service. For the time being i cannot reproduce. 
You can check [vite-vue-sqlite-app](https://github.com/jepiqueau/vite-vue-sqlite-app) this is the app i am trying to reproduce the issue

**Comment by jepiqueau** [comment] 2023-05-09 12:47
@michaelgoeke it happened twice only in a lot of trials without really finding the right process to make it happen. So hard to find the reason and to fix it.

**Comment by michaelgoeke** [comment] 2023-05-09 16:16
Using that repository, if I'm able to reproduce it every time using the follow steps
given:
git clone https://github.com/jepiqueau/vite-vue-sqlite-app.git
npm i

steps to reproduce:
yarn dev
run chrome, goto localhost:5173
open dev tools on separate (undocked) window
minimize chrome, set focus to devtools separate window
press F5 to reload page, error occurs in console
> Uncaught (in promise) Error: Error: Error: >>> jeep-sqlite StoreName: undefined is not opened
>    at main.ts:50:15
> (anonymous) @ main.ts:50

press F5 to reproduce over and over.

**Comment by jepiqueau** [comment] 2023-05-15 08:59
@michaelgoeke Did you test the new release? if yes and if it works can you please close the issue.

**Comment by michaelgoeke** [comment] 2023-05-15 15:44
Will do.  The update will get rolled into our project and we'll see if the issues are fixed (they were primarily intermittent test failures running playwright with multiple threads on a test vm). Give us a few days so we can see how things pan out and then I'll respond and likely just close it.
Thanks!

**Comment by jepiqueau** [comment] 2023-05-21 17:04
@michaelgoeke i will close it reopen it if require

**Closed by jepiqueau** 2023-05-21 17:04 UTC

**Comment by michaelgoeke** [comment] 2023-05-24 00:22
Thanks for closing this - it looks like it's resolved our issue. Again, thanks for being responsive and being able to fix it!

**Comment by jepiqueau** [comment] 2023-05-24 03:59
@michaelgoeke you are welcome
