### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'lastId')"

### ISSUE THREAD

**Issue by narianangel** [capacitor-community/sqlite#479] opened 2023-10-10 12:33 UTC
**Describe the bug**
Im using last Capacitor-community/sqlite version and when I try to use "executeSet" to UPDATE multiples statements I always get a error:

`TypeError: Cannot read properties of undefined (reading 'lastId')"`

My current code for that:

`async executeSetSql(setSql: Array<any>): Promise<any> {
    try {
      let result = await this.db?.executeSet(setSq);
      return result;
    } catch (err) {
      return Promise.reject(err);
    }
  }`

Platform tested: **Electron**

With previous version (4.6.3) this was working fine...

**Comment by jepiqueau** [comment] 2023-10-11 06:42
@narianangel  can you specify the platform Electron,iOS,Android

**Comment by narianangel** [comment] 2023-10-11 12:20
I had to change to work, but my old code was some like:

**STATEMENTES**
`[
	{
		statement: "INSERT INTO test_table (column1, column2) VALUES (?,?);",
		values: [
			'test1',
			'test2',
		]
	},
	{
		statement: "INSERT INTO test_table (column1, column2) VALUES (?,?);",
		values: [
			'test1',
			'test2',
		]
	},
	{
		statement: "INSERT INTO test_table (column1, column2) VALUES (?,?);",
		values: [
			'test1',
			'test2',
		]
	}
]`
**FUNCTION TO EXECUTE**

`async executeSetSql(setSql: Array<any>): Promise<any> {
    try {
      let result = await this.db?.executeSet(setSql);
      return result;
    } catch (err) {
      return Promise.reject(err);
    }
  }`

**Comment by jepiqueau** [comment] 2023-10-11 17:06
@narianangel I could not reproduce the error

**Comment by narianangel** [comment] 2023-10-11 17:19
Test it with "UPDATE" instead "INSERT".

If not, dont worry... I changed my logic to use **executeSql** instead **executeSetSql**, even if I need to insert/update/delete multiples rows.

**Comment by jepiqueau** [comment] 2023-10-12 07:51
@narianangel Even with UPDATE i could not reproduce it. So i close the issue fill free to re-open it if required.

**Closed by jepiqueau** 2023-10-12 07:51 UTC
